CREATE SCHEMA ECIV_SI1N;

USE ECIV_SI1N;

CREATE TABLE ALUNOS (
ALUNO_ID INT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
CPF VARCHAR(11) UNIQUE NOT NULL,
DATA_NASCIMENTO DATE,
FORNEC_RUA VARCHAR(45) NOT NULL,
ALUNO_NUMRUA INT,
ALUNO_BAIRRO VARCHAR(45) NOT NULL,
ALUNO_CIDADE VARCHAR(45) NOT NULL,
ALUNO_ESTADO VARCHAR(45) NOT NULL,
ALUNO_PAIS VARCHAR(30) NOT NULL,
);

CREATE TABLE INSTRUTORES (
INSTRUTOR_ID INT  PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
ESPECIALIDADE VARCHAR(50),
CONTRATO VARCHAR(100)
);

CREATE TABLE MODALIDADES (
MODALIDADES_ID INT  PRIMARY KEY,
NOME_MODALIDADE VARCHAR(50) NOT NULL,
DESCRIÇÃO TEXT
DURAÇÃO VARCHAR(25) NOT NULL
);

CREATE TABLE PLANOS_DE_TREINAMENTOS (
PLANO_ID INT PRIMARY KEY,
ALUNO_ID INT,
INSTRUTOR_ID INT,
DESCRIÇÃO TEXT,
DATA_INICIO DATE,
DATA_FIM DATE,
CONSTRAINT FLPR_FK_ALUNOS FOREIGN KEY (ALUNO_ID) REFERENCES ALUNOS(ALUNO_ID) ,
CONSTRAINT FLPR_FK_INSTRUTORES FOREIGN KEY (INSTRUTOR_ID) REFERENCES INSTRUTORES(INSTRUTOR_ID) ,
);

CREATE TABLE AULAS (
AULA_ID INT PRIMARY KEY,
MODALIDADE_ID INT,
INSTRUTOR_ID INT,
HORARIO DATETIME NOT NULL,
CAPACIDADE INT NOT NULL,
CONSTRAINT FLPR_FK_MODALIDADE FOREIGN KEY (MODALIDADE_ID) REFERENCES MODALIDADE(MODALIDADE_ID) ,
CONSTRAINT FLPR_FK_INSTRUTORES FOREIGN KEY (INSTRUTOR_ID) REFERENCES INSTRUTORES(INSTRUTOR_ID) ,
);

CREATE TABLE PAGAMENTOS (
PAGAMENTO_ID INT PRIMARY KEY,
ALUNO_ID INT,
DATA_PAGAMENTO DATE NOT NULL,
VALOR DECIMAL(10, 2) NOT NULL,
HORA_PAG TIME NOT NULL,
CONFIRM_PAG NOT NULL,
STATUS_PAGAMENTO ENUM('pago', 'pendente') DEFAULT 'pendente',
CONSTRAINT FLPR_FK_ALUNOS FOREIGN KEY (ALUNO_ID) REFERENCES ALUNOS(ALUNO_ID) 
);

CREATE TABLE Aulas_Alunos (
AULA_ID INT PRIMARY KEY,
ALUNO_ID INT PRIMARY KEY,
DATA_MATRICULA DATE,
CONSTRAINT FLPR_FK_AULAS FOREIGN KEY (AULA_ID) REFERENCES AULAS(AULA_ID) ,
CONSTRAINT FLPR_FK_ALUNOS FOREIGN KEY (ALUNO_ID) REFERENCES ALUNOS(ALUNO_ID) 
);

ALTER TABLE ALUNOS ADD ALUNO_TELEFONE VARCHAR(50);
ALTER TABLE ALUNOS DROP CPF;
ALTER TABLE ALUNOS MODIFY NOME VARCHAR(100) NOT NULL;
ALTER TABLE ALUNOS CHANGE NOME ALUNO_NOME VARCHAR(50) NOT NULL;

ALTER TABLE INSTRUTORES ADD EMAIL VARCHAR(100);
ALTER TABLE INSTRUTORES DROP CONTRATO;
ALTER TABLE INSTRUTORES MODIFY MODIFY ESPECIALIDADE VARCHAR(100);
ALTER TABLE INSTRUTORES CHANGE NOME NOME_COMPLETO VARCHAR(150) NOT NULL;

ALTER TABLE MODALIDADES ADD DURACAO INT;
ALTER TABLE MODALIDADES DROP DESCRICAO;
ALTER TABLE MODALIDADES MODIFY NOME_MODALIDADE VARCHAR(100) NOT NULL; 
ALTER TABLE MODALIDADES CHANGE DURAÇÃO_MODALIDADE VARCHAR(30) NOT NULL;

ALTER TABLE PLANOS_DE_TREINAMENTOS ADD FREQUENCIA_SEMANAL INT;
ALTER TABLE PLANOS_DE_TREINAMENTOS DROP DESCRICAO;
ALTER TABLE PLANOS_DE_TREINAMENTOS MODIFY DATA_INICIO DATETIME;
ALTER TABLE PLANOS_DE_TREINAMENTOS CHANGE DATA_FIM DATA_TERMINO DATE;

ALTER TABLE AULAS ADD LOCAL VARCHAR(100);
ALTER TABLE AULAS DROP CAPACIDADE;
ALTER TABLE AULAS MODIFY LOCAL VARCHAR(50);
ALTER TABLE AULAS CHANGE LOCAL AULA_LOCAL VARCHAR(100);

ALTER TABLE PAGAMENTOS ADD STATUS_PAG VARCHAR(20) NOT NULL;
ALTER TABLE PAGAMENTOS DROP COLUMN HORA_PAG TIME NOT NULL;
ALTER TABLE PAGAMENTOS MODIFY COLUMN  STATUS_PAG ENUM('PENDENTE', 'CONCLUIDO', 'EM ESPERA');
ALTER TABLE PAGAMENTOS CHANGE COLUMN CONFIRM_PAG ID_PAG INT PRIMARY KEY;
