CREATE SCHEMA ECIV_SI1N;

USE ECIV_SI1N;

CREATE TABLE ALUNOS (
ALUNO_ID INT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
CPF CHAR(11) UNIQUE NOT NULL,
DATA_NASCIMENTO DATE,
FORNEC_RUA VARCHAR(45) NOT NULL,
ALUNO_NUMRUA INT,
ALUNO_BAIRRO VARCHAR(45) NOT NULL,
ALUNO_CIDADE VARCHAR(45) NOT NULL,
ALUNO_ESTADO VARCHAR(45) NOT NULL,
ALUNO_PAIS VARCHAR(30) NOT NULL,
);

CREATE TABLE INSTRUTORES (
INSTRUTOR_ID INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
ESPECIALIDADE VARCHAR(50),
CONTRATO VARCHAR(100)
);

CREATE TABLE MODALIDADES (
MODALIDADES_ID INT AUTO_INCREMENT PRIMARY KEY,
NOME_MODALIDADE VARCHAR(50) NOT NULL,
DESCRIÇÃO TEXT
);

CREATE TABLE Planos_de_Treinamento (
PLANO_ID INT AUTO_INCREMENT PRIMARY KEY,
ALUNO_ID INT,
INSTRUTOR_ID INT,
DESCRIÇÃO TEXT,
DATA_INICIO DATE,
DATA_FIM DATE,
CONSTRAINT FLPR_FK_ALUNOS FOREIGN KEY (ALUNO_ID) REFERENCES ALUNOS(ALUNO_ID) ,
CONSTRAINT FLPR_FK_INSTRUTORES FOREIGN KEY (INSTRUTOR_ID) REFERENCES INSTRUTORES(INSTRUTOR_ID) ,
);

CREATE TABLE AULAS (
AULA_ID INT AUTO_INCREMENT PRIMARY KEY,
MODALIDADE_ID INT,
INSTRUTOR_ID INT,
HORARIO DATETIME NOT NULL,
CAPACIDADE INT NOT NULL,
CONSTRAINT FLPR_FK_MODALIDADE FOREIGN KEY (MODALIDADE_ID) REFERENCES MODALIDADE(MODALIDADE_ID) ,
CONSTRAINT FLPR_FK_INSTRUTORES FOREIGN KEY (INSTRUTOR_ID) REFERENCES INSTRUTORES(INSTRUTOR_ID) ,
);

CREATE TABLE PAGAMENTOS (
PAGAMENTO_ID INT AUTO_INCREMENT PRIMARY KEY,
ALUNO_ID INT,
DATA_PAGAMENTO DATE NOT NULL,
VALOR DECIMAL(10, 2) NOT NULL,
STATUS_PAGAMENTO ENUM('pago', 'pendente') DEFAULT 'pendente',
CONSTRAINT FLPR_FK_ALUNOS FOREIGN KEY (ALUNO_ID) REFERENCES ALUNOS(ALUNO_ID) 
);

CREATE TABLE Aulas_Alunos (
AULA_ID INT,
ALUNO_ID INT,
DATA_MATRICULA DATE,
PRIMARY KEY (AULA_ID,ALUNO_ID),
CONSTRAINT FLPR_FK_AULAS FOREIGN KEY (AULA_ID) REFERENCES AULAS(AULA_ID) ,
CONSTRAINT FLPR_FK_ALUNOS FOREIGN KEY (ALUNO_ID) REFERENCES ALUNOS(ALUNO_ID) 
);
