CREATE SCHEMA EC1_SI1N;

CREATE TABLE IF NOT EXISTS CLIENTES (
CLIENTES_ID INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
CPF CHAR(11) UNIQUE NOT NULL,
DATA_NASCIMENTO DATE,
STATUS_FIDELIDADE NOT NULL,
CLIEN_RUA VARCHAR(45) NOT NULL,
CLIEN_BAIRRO VARCHAR(45) NOT NULL,
CLIEN_CIDADE VARCHAR(45) NOT NULL,
CLIEN_ESTADO VARCHAR(45) NOT NULL,
CLIEN_PAIS VARCHAR(30) NOT NULL,
  
);

CREATE TABLE IF NOT EXISTS FORNECEDORES (
FORNE_id INT PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(100) NOT NULL,
CONTAT VARCHAR (100),
STATUS_FIDELIDADE NOT NULL,
FORNE_RUA VARCHAR(45) NOT NULL,
FORNE_BAIRRO VARCHAR(45) NOT NULL,
FORNE_CIDADE VARCHAR(45) NOT NULL,
FORNE_ESTADO VARCHAR(45) NOT NULL,
FORNE_PAIS VARCHAR(30) NOT NULL,
);

CREATE TABLE IF NOT EXISTS PRODUTOS (
PRODUTO_ID INT AUTO_INCREMENT PRIMARY KEY,
nome_produto VARCHAR(100) NOT NULL,
categoria VARCHAR(50),
PREÇO DECIMAL(10, 2) NOT NULL,
ESTOQUE INT DEFAULT 0,
FORNECEDOR_ID INT,
FOREIGN KEY (FORNECEDOR_ID) REFERENCES FORNECEDORES(FORNECEDOR_ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS VENDAS (
VENDA_ID INT AUTO_INCREMENT PRIMARY KEY,
CLIENTE_ID INT,
DATA_VENDA DATE NOT NULL,
FORMA_PAGAMENTO  NOT NULL,
FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_IDd) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Pagamentos (
PAGAMENTO_ID INT  PRIMARY KEY,
VENDA_ID INT,
DATA_PAGAMENTO DATE NOT NULL,
VALOR DECIMAL(10, 2) NOT NULL,
STATUS_PAGAMENTO DEFAULT ,
FOREIGN KEY (venda_id) REFERENCES Vendas(venda_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Vendas_Produtos (
VENDA_ID INT,
PRODUTO_id INT,
QUANTIDADE INT NOT NULL,
PRIMARY KEY (VENDA_ID, PRODUTO_ID),
FOREIGN KEY (VENDA_ID) REFERENCES VENDAS(VENDAS_ID) ON DELETE CASCADE,
FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(PRODUTO_ID) ON DELETE CASCADE
