   CREATE SCHEMA ECII_SI1N;

USE EC1_SI1N;

CREATE TABLE IF NOT EXISTS Passageiros(
Passag_CPF INT PRIMARY KEY,
Passag_NOME VARCHAR(45) NOT NULL,
Passag_RUA VARCHAR(45) NOT NULL,
Passag_NUMRUA INT,
Passag_BAIRRO VARCHAR(45) NOT NULL,
Passag_CIDADE VARCHAR(45) NOT NULL,
Passag_ESTADO VARCHAR(45) NOT NULL,
Passag_PAIS VARCHAR(30) NOT NULL,
Passag_CODPOSTAL VARCHAR(10) NOT NULL,
Passag_TELEFONE VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS Voos(
Voos_COD INT PRIMARY KEY,
Voos_DESTINO VARCHAR(50) NOT NULL,
Voos_HR_PARTIDA VARCHAR(15) NOT NULL,
Voos_HR_CHEGADA VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS Aeroportos(
Aeroportos_COD INT PRIMARY KEY,
Aeroportos_NOME VARCHAR(50) NOT NULL,
Aeroportos_LOCAL VARCHAR(50) NOT NULL,
Aeroportos_PAIS VARCHAR(50) NOT NULL,
Aeroportos_LONGITUDE VARCHAR(20) NOT NULL,
Aeroportos_LATITUDE VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS Aeronave(
Aeronave_COD INT PRIMARY KEY,
Aeronave_CAPACIDADE VARCHAR(100) NOT NULL,
Aeronave_ANOFAIR VARCHAR(50) NOT NULL,
Aeronave_MODELO VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS Funcionario(
Funcionario_COD INT PRIMARY KEY,
Funcionario_FUNCAO VARCHAR(30) NOT NULL,
Funcionario_NOME VARCHAR(30) NOT NULL,
Funcionario_TELEFONE VARCHAR(30) NOT NULL,
Funcionario_DATANASC VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS Reserva(
Voos_COD
Passag_CPF
);
